repository:
  name: {{ REPO_NAME }}
  description: ''
  homepage: ''
  private: true
  has_issues: false
  has_wiki: false
  has_downloads: false
  default_branch: develop
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: false

labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699

collaborators:
  - username: timlangley
    permission: push

  - username: dblencowe
    permission: admin

branches:
  - name: master
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts: ['WIP']
      restrictions:
        users: []
        teams: []
  - name: develop
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts: ['WIP']
      restrictions:
        users: [
          'timlangley'
        ]
        teams: []
